name: Create MPAS mesh decompositions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build-metis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake build-essential

      - name: Clone GKlib Source
        run: |
          git clone https://github.com/KarypisLab/GKlib.git
          cd GKlib

      - name: Configure and Build GKlib
        run: |
          cd GKlib
          make config prefix=/home/runner/
          make
          make install
          echo "LD_LIBRARY_PATH=/GKlib/runner/METIS/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PATH=/home/runner/GKlib/bin:$PATH" >> $GITHUB_ENV

      - name: Clone METIS Source
        run: |
          git clone https://github.com/KarypisLab/METIS.git
          cd METIS

      - name: Configure and Build METIS
        run: |
          cd METIS
          make config cc=gcc prefix=/home/runner/ gklib_path=/home/runner/
          make
          make install
          echo "LD_LIBRARY_PATH=/home/runner/METIS/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PATH=/home/runner/METIS/bin:$PATH" >> $GITHUB_ENV

      - name: Display
        run: |
          ls /home/runner/
          where gpmetis

      - name: Download MPAS static file
        run: |
          wget https://www2.mmm.ucar.edu/projects/mpas/atmosphere_meshes/x1.40962_static.tar.gz
          tar -xvf x1.40962_static.tar.gz

      - name: Create decompositions
        run: |
          gpmetis -minconn -contig -niter=200 data/x1.40962.graph.info 12