name: Create MPAS mesh decompositions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build-decomp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mesh: [40962]
        include:
        - mesh: 40962
          decomps: '12 24 36 48 60 72'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake build-essential

#      - name: Cache GKlib
#        id: cache-GKlib
#        uses: actions/cache@v4
#        with:
#          path: /home/runner/GKlib/lib
#          key: cache-GKlib-key

      - name: Configure and Build GKlib
        if: steps.cache-GKlib.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/KarypisLab/GKlib.git
          cd GKlib
          make config prefix=/home/runner/GKlib
          make
          make install

#      - name: Cache METIS
#        id: cache-METIS
#        uses: actions/cache@v4
#        with:
#          path: /home/runner/METIS/lib
#          key: cache-METIS-key
 
      - name: Configure and Build METIS
        if: steps.cache-METIS.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/KarypisLab/METIS.git
          cd METIS
          make config cc=gcc prefix=/home/runner/METIS gklib_path=/home/runner/GKlib
          make
          make install

      - name: Display PATH
        run: |
          echo "LD_LIBRARY_PATH=/home/runner/GKlib/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PATH=/home/runner/GKlib/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/home/runner/METIS/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PATH=/home/runner/METIS/bin:$PATH" >> $GITHUB_ENV
          echo $PATH
          echo $LD_LIBRARY_PATH
          echo "------------/home/runner/METIS/lib"
          ls /home/runner/METIS/lib
          echo "------------/home/runner/GKlib/lib"
          ls /home/runner/GKlib/lib

      - name: Download MPAS static file
        run: |
          wget -q https://www2.mmm.ucar.edu/projects/mpas/atmosphere_meshes/x1.${{matrix.mesh}}_static.tar.gz
          tar -xvf x1.${{matrix.mesh}}_static.tar.gz

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9.12

      - name: Create decompositions
        run: |
          pwd
          ./create_decomp.py -m ${{matrix.mesh}} -d ${{matrix.decomps}}
          ls
