name: Create MPAS mesh decompositions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build-metis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake build-essential

      - name: Cache GKlib
        id: cache-GKlib
        uses: actions/cache@v4
        with:
          path: /home/runner/GKlib
          key: cache-GKlib-key

      - name: Configure and Build GKlib
        if: steps.cache-GKlib.outputs.cache-hit != 'false'
        run: |
          git clone https://github.com/KarypisLab/GKlib.git
          cd GKlib
          make config prefix=/home/runner/
          make
          make install
          echo "LD_LIBRARY_PATH=/home/runner/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PATH=/home/runner/bin:$PATH" >> $GITHUB_ENV

      - name: Cache METIS
        id: cache-METIS
        uses: actions/cache@v4
        with:
          path: /home/runner/METIS
          key: cache-METIS-key
 
      - name: Configure and Build METIS
        if: steps.cache-METIS.outputs.cache-hit != 'false'
        run: |
          git clone https://github.com/KarypisLab/METIS.git
          cd METIS
          make config cc=gcc prefix=/home/runner/ gklib_path=/home/runner/
          make
          make install
          echo "LD_LIBRARY_PATH=/home/runner/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PATH=/home/runner/bin:$PATH" >> $GITHUB_ENV

      - name: Display lib
        run: |
          ls /home/runner/lib

      - name: Display bin
        run: |
          ls /home/runner/bin

      - name: Display PATH
        run: |
          echo $PATH

      - name: Download MPAS static file
        run: |
          wget https://www2.mmm.ucar.edu/projects/mpas/atmosphere_meshes/x1.40962_static.tar.gz
          tar -xvf x1.40962_static.tar.gz

#      - name: Create decompositions
#        run: |
#          gpmetis -minconn -contig -niter=200 data/x1.40962.graph.info 12